aptly_service_user: aptly
aptly_service_group: aptly

# For uploads into aptly incoming folder
aptly_uploaders_group: aptly-uploaders
aptly_uploaders:
  - { user: 'james-urepo', display: 'James Lu' }
  - { user: 'unit193',     display: 'Unit 193' }

# Note: much of utopia-scripts is hardcoded to assume /srv/aptly so far...
aptly_base_path: "/srv/aptly"

# Paths for incoming uploads
aptly_incoming_path: "/srv/aptly-incoming"
aptly_incoming_dists:
- sid
- sid-imports
- sid-meta
- buster
- buster-imports

# server_name entries for nginx
nginx_server_names:
  - deb.utopia-repository.org
  - ni.deb.utopia-repository.org  # nightlies
nginx_server_names_redirect:
  - utopia-repository.org
  - www.utopia-repository.org
nginx_use_https: true
nginx_ssl_cert: /etc/ssl/urepo.crt
nginx_ssl_key: /etc/ssl/urepo.key
