repo_hosts:
  children:
    repo_master:
      hosts:
        deb-master.utopia-repository.org:
          server_description: "Los Angeles, CA, US"
          ansible_host: lax02.jlu5.com
    repo_mirrors:
      hosts:
        deb2.utopia-repository.org:
          server_description: "Amsterdam, NL"
          ansible_host: ams02.jlu5.com
