repo_hosts:
  children:
    repo_master:
      hosts:
        deb-master.utopia-repository.org:
          server_description: "Montreal, QC, CA"
          ansible_host: 15.235.106.198
    repo_mirrors:
      hosts:
        deb2.utopia-repository.org:
          server_description: "Amsterdam, NL"
          ansible_host: ams02.jlu5.com
