repo_hosts:
  children:
    repo_master:
      hosts:
        deb0.utopia-repository.org:
          server_description: "Los Angeles, CA, US"
    repo_mirrors:
      hosts:
        deb1.utopia-repository.org:
          server_description: "Tampa, FL, US"
        deb2.utopia-repository.org:
          server_description: "Amsterdam, NL"
