- name: Create aptly group
  group:
    name: "{{ aptly_service_group }}"
    state: present

- name: Create aptly service user
  user:
    name: "{{ aptly_service_user }}"
    group: "{{ aptly_service_group }}"
    password_lock: true
    shell: "/bin/bash"
  register: _aptly_user

- name: Create aptly data folder
  file:
    path: "{{ aptly_base_path }}"
    state: directory
    owner: "{{ aptly_service_user }}"
    group: "{{ aptly_service_group }}"

- name: Create aptly config folder
  file:
    path: "{{ aptly_config_path }}"
    state: directory
    owner: "{{ aptly_service_user }}"
    group: "{{ aptly_service_group }}"
    mode: "0750"
