- name: Create certificates folder for certpush
  file:
    path: "{{ nginx_ssl_dir }}"
    state: directory
    owner: "{{ nginx_ssl_dir_owner | default(lookup('env', 'USER'), true) }}"
    group: "{{ nginx_ssl_dir_group }}"
    mode: "0700"
  when: nginx_ssl_dir | default("")

- name: Generate certpush config
  local_action:
    module: template
    src: "certpush.config.sh.j2"
    dest: "{{ playbook_dir }}/certpush-files/certpush.config.sh"
  run_once: true
  become: false
