- name: Install aptly and packaging prerequisites
  apt:
    package:
    - aptly
    - build-essential
    - devscripts
    - gnupg
    - graphviz
    state: present
    install_recommends: yes
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create aptly uploaders group
  group:
    name: "{{ aptly_uploaders_group }}"
    state: present

- name: Template aptly.conf
  template:
    src: "aptly.conf.j2"
    dest: "/etc/aptly.conf"
    mode: "0644"

# aptly's backend expects this to exist, even when using a test repo with signing disabled!
# Note: configuring the actual key is out of the scope for this playbook
- name: Create gnupg home dir
  file:
    path: "{{ _aptly_user.home }}/.gnupg"
    state: directory
    owner: "{{ aptly_service_user }}"
    group: "{{ aptly_service_group }}"
    mode: "0700"

- name: Clone utopia-scripts repo
  git:
    repo: "https://github.com/utopia-repository/utopia-scripts/"
    dest: "{{ _aptly_user.home }}/utopia-scripts"
  become_user: "{{ aptly_service_user }}"
